/** Comptes démo — une branche par rôle (dev / démo uniquement) */
export const DEMO_ACCOUNTS = [
  {
    id: 'patient',
    role: 'patient',
    label: 'Patient',
    email: 'patient@e-sante.sn',
    password: 'Patient123!',
    description: 'Rappels, annuaire, pharmacie',
  },
  {
    id: 'medecin',
    role: 'medecin',
    label: 'Médecin',
    email: 'dr.fatou@e-sante.sn',
    password: 'Medecin123!',
    description: 'Cardiologie, RDV, services',
  },
  {
    id: 'aide_soignant',
    role: 'medecin',
    label: 'Aide-soignant(e)',
    email: 'aide@e-sante.sn',
    password: 'Medecin123!',
    description: 'Aide à domicile, soins',
  },
  {
    id: 'pharmacie',
    role: 'pharmacie',
    label: 'Pharmacie',
    email: 'pharma@e-sante.sn',
    password: 'Pharmacie123!',
    description: 'Catalogue, chat, réservations',
  },
  {
    id: 'hopital',
    role: 'hopital',
    label: 'Hôpital',
    email: 'hopital@e-sante.sn',
    password: 'Pharmacie123!',
    description: 'Services, équipe, urgences',
  },
  {
    id: 'clinique',
    role: 'clinique',
    label: 'Clinique',
    email: 'clinique@e-sante.sn',
    password: 'Pharmacie123!',
    description: 'Affiliations, tarifs, RDV',
  },
  {
    id: 'admin',
    role: 'admin',
    label: 'Admin',
    email: 'admin@e-sante.sn',
    password: 'Admin123!',
    description: 'Validation & alertes MINSANTE',
  },
];
