/** API endpoint constants */
const ENDPOINTS = {
    auth: {
        login: '/auth/login',
        register: '/auth/register',
        refresh: '/auth/refresh',
        me: '/auth/me',
        forgotPassword: '/auth/forgot-password',
        resetPassword: '/auth/reset-password',
        changePassword: '/auth/change-password',
        otpSend: '/auth/otp/envoyer',
        otpVerify: '/auth/otp/verifier',
        smsConfig: '/auth/sms-config',
        resetPasswordSms: '/auth/reset-password-sms',
    },
    inscriptions: {
        professionnel: '/inscriptions/professionnel',
        documentsRequis: '/inscriptions/documents-requis',
        statut: '/inscriptions/statut',
        valider: (id) => `/inscriptions/admin/${id}/valider`,
        rejeter: (id) => `/inscriptions/admin/${id}/rejeter`,
        preVerifier: (id) => `/inscriptions/admin/${id}/pre-verifier`,
        adminEnAttente: '/inscriptions/admin/en-attente',
    },
    publications: {
        featured: '/publications/featured',
        alertes: '/publications/alertes',
        base: '/publications',
        like: (id) => `/publications/${id}/like`,
        comments: (id) => `/publications/${id}/comments`,
    },
    fichiers: {
        byId: (id) => `/fichiers/${id}`,
    },
    patients: {
        profile: '/patients/profile',
        mePhoto: '/patients/me/photo',
        parametresVie: '/patients/parametres-vie',
        export: '/patients/export',
        account: '/patients/account',
        privacy: '/patients/privacy',
    },
    carnetMedical: {
        me: '/carnet-medical/me',
        textes: '/carnet-medical/textes-consentement',
        consentements: '/carnet-medical/me/consentements',
        observations: '/carnet-medical/me/observations',
    },
    traitements: {
        base: '/traitements',
        byId: (id) => `/traitements/${id}`,
        statut: (id) => `/traitements/${id}/statut`,
    },
    prises: {
        aujourdhui: '/prises/aujourd-hui',
        confirmer: (id) => `/prises/${id}/confirmer`,
        history: '/prises/historique',
    },
    ordonnances: {
        base: '/ordonnances',
        scan: '/ordonnances/scan',
        pharmacie: '/ordonnances/pharmacie',
        byId: (id) => `/ordonnances/${id}`,
        valider: (id) => `/ordonnances/${id}/valider`,
    },
    ordonnancesElec: {
        base: '/ordonnances-electroniques',
        signer: (id) => `/ordonnances-electroniques/${id}/signer`,
        medecin: '/ordonnances-electroniques/medecin',
        patient: '/ordonnances-electroniques/patient',
        verifier: (numero) => `/ordonnances-electroniques/verifier/${numero}`,
        delivrer: (id) => `/ordonnances-electroniques/${id}/delivrer`,
        audit: (id) => `/ordonnances-electroniques/${id}/audit`,
        document: (id) => `/ordonnances-electroniques/${id}/document`,
        telecharger: (id) => `/ordonnances-electroniques/${id}/telecharger`,
        disponibilite: (id, etabId) => `/ordonnances-electroniques/${id}/disponibilite?etablissement_id=${etabId}`,
        reserver: (id) => `/ordonnances-electroniques/${id}/reserver`,
    },
    statistiques: {
        observance: '/statistiques/observance',
        tendances: '/statistiques/tendances',
        risque: '/statistiques/risque',
    },
    etablissements: {
        base: '/etablissements',
        byId: (id) => `/etablissements/${id}`,
        horaires: (id) => `/etablissements/${id}/horaires`,
        publications: (id) => `/etablissements/${id}/publications`,
        pharmacieDashboard: '/etablissements/pharmacie/dashboard',
        structureDashboard: '/etablissements/structure/dashboard',
        meProfil: '/etablissements/me/profil',
        meHoraires: '/etablissements/me/horaires',
        meGarde: '/etablissements/me/garde',
        meLocalisation: '/etablissements/me/localisation',
        mePhoto: '/etablissements/me/photo',
        meMedecins: '/etablissements/me/medecins',
        meServices: '/etablissements/me/services',
        meRendezVous: '/etablissements/me/rendez-vous',
        serviceById: (id) => `/etablissements/me/services/${id}`,
        medecinById: (id) => `/etablissements/me/medecins/${id}`,
        inviterMedecin: '/etablissements/me/affiliations/inviter',
        meAffiliations: '/etablissements/me/affiliations',
        meEquipe: '/etablissements/me/equipe',
        equipeById: (id) => `/etablissements/me/equipe/${id}`,
        equipePublic: (id) => `/etablissements/${id}/equipe`,
    },
    medecins: {
        base: '/medecins',
        byId: (id) => `/medecins/${id}`,
        meProfile: '/medecins/me/profile',
        meDashboard: '/medecins/me/dashboard',
        meProfil: '/medecins/me/profile',
        meHoraires: '/medecins/me/horaires',
        mePhoto: '/medecins/me/photo',
        meCachet: '/medecins/me/cachet',
        meSignature: '/medecins/me/signature',
        carnetPatient: (patientId) => `/medecins/patients/${patientId}/carnet`,
        meAffiliations: '/medecins/me/affiliations',
        meCabinet: '/medecins/me/cabinet',
        repondreAffiliation: (id) => `/medecins/me/affiliations/${id}/repondre`,
        terminerAffiliation: (id) => `/medecins/me/affiliations/${id}/terminer`,
        updateAffiliation: (id) => `/medecins/me/affiliations/${id}`,
        meParcours: '/medecins/me/parcours',
        parcoursById: (id) => `/medecins/me/parcours/${id}`,
        creneaux: (id) => `/rendez-vous/medecins/${id}/creneaux`,
    },
    rendezVous: {
        base: '/rendez-vous',
        mesRdv: '/rendez-vous/mes-rdv',
        medecin: '/rendez-vous/medecin',
        statut: (id) => `/rendez-vous/${id}/statut`,
        contreProposition: (id) => `/rendez-vous/${id}/contre-proposition`,
        reponseProposition: (id) => `/rendez-vous/${id}/reponse-proposition`,
        annuler: (id) => `/rendez-vous/${id}`,
        annulationPreview: (id) => `/rendez-vous/${id}/annulation-preview`,
        byId: (id) => `/rendez-vous/${id}`,
        video: (id) => `/rendez-vous/${id}/video`,
    },
    produits: {
        base: '/produits',
        mesProduits: '/produits/mes-produits',
        etablissement: (id) => `/produits/etablissement/${id}`,
        pharmacie: (id) => `/produits/pharmacie/${id}`,
        recherche: '/produits/recherche',
        byId: (id) => `/produits/${id}`,
    },
    avis: { base: '/avis' },
    messagerie: {
        pharmacies: '/messagerie/pharmacies',
        etablissements: '/messagerie/etablissements',
        conversations: '/messagerie/conversations',
        demarrer: (pharmacieId) => `/messagerie/pharmacies/${pharmacieId}/conversations`,
        demarrerEtab: (id) => `/messagerie/etablissements/${id}/conversations`,
        conversation: (id) => `/messagerie/conversations/${id}`,
        message: (id) => `/messagerie/conversations/${id}/messages`,
        pharmacieConversations: '/messagerie/pharmacie/conversations',
        pharmacieConversation: (id) => `/messagerie/pharmacie/conversations/${id}`,
        pharmacieMessage: (id) => `/messagerie/pharmacie/conversations/${id}/messages`,
        structureConversations: '/messagerie/structure/conversations',
        structureConversation: (id) => `/messagerie/structure/conversations/${id}`,
        structureMessage: (id) => `/messagerie/structure/conversations/${id}/messages`,
    },
    notifications: {
        me: '/notifications/me',
        pushVapidKey: '/notifications/push/vapid-public-key',
        pushSubscribe: '/notifications/push/subscribe',
        pushUnsubscribe: '/notifications/push/unsubscribe',
    },
    reservations: {
        base: '/reservations-dispensaire',
        estimer: '/reservations-dispensaire/estimer',
        mesReservations: '/reservations-dispensaire/mes-reservations',
        etablissement: '/reservations-dispensaire/etablissement',
        statut: (id) => `/reservations-dispensaire/${id}/statut`,
        annuler: (id) => `/reservations-dispensaire/${id}`,
        annulationPreview: (id) => `/reservations-dispensaire/${id}/annulation-preview`,
    },
    ai: {
        chat: '/ai/chat',
        status: '/ai/status',
        bookRdv: '/ai/book-rdv',
    },
    commissions: {
        tarifs: '/commissions/tarifs',
        previewConsultation: '/commissions/preview/consultation',
        previewPharmacie: '/commissions/preview/pharmacie',
        adminResume: '/commissions/admin/resume',
        adminTransactions: '/commissions/admin/transactions',
        adminReversements: '/commissions/admin/reversements/traiter',
    },
    urgence: {
        types: '/urgence/types',
        protocole: (type) => `/urgence/protocole/${type}`,
        etablissements: '/urgence/etablissements',
    },
    demandes: {
        base: '/demandes-prise-en-charge',
        mesDemandes: '/demandes-prise-en-charge/mes-demandes',
        etablissement: '/demandes-prise-en-charge/etablissement',
        reponse: (id) => `/demandes-prise-en-charge/${id}/reponse`,
        annuler: (id) => `/demandes-prise-en-charge/${id}`,
    },
    paiements: {
        config: '/paiements/config',
        initier: '/paiements/initier',
        simuler: (id) => `/paiements/${id}/simuler`,
        statut: (id) => `/paiements/${id}/statut`,
        recu: (id) => `/paiements/${id}/recu`,
        liste: '/paiements/mes-paiements',
    },
    admin: {
        auditLogs: '/admin/audit-logs',
        overview: '/admin/overview',
        comptes: '/admin/comptes',
        etablissements: '/admin/etablissements',
        alertes: '/admin/alertes-sanitaires',
        regions: '/admin/regions',
        santePublique: '/admin/sante-publique',
    },
    famille: {
        base: '/famille',
        detail: (id) => `/famille/${id}`,
    },
    qrMedical: {
        me: '/qr-medical/me/qr',
        regenerer: '/qr-medical/me/regenerer',
        public: (token) => `/qr-medical/${token}`,
    },
};

export default ENDPOINTS;
