const express = require('express');
const router = express.Router();

const authRoutes = require('./auth.routes');
const patientRoutes = require('./patient.routes');
const traitementRoutes = require('./traitement.routes');
const priseRoutes = require('./prise.routes');
const ordonnanceRoutes = require('./ordonnance.routes');
const statistiqueRoutes = require('./statistique.routes');
const etablissementRoutes = require('./etablissement.routes');
const medecinRoutes = require('./medecin.routes');
const avisRoutes = require('./avis.routes');
const messagerieRoutes = require('./messagerie.routes');
const fichierRoutes = require('./fichier.routes');
const rendezvousRoutes = require('./rendezvous.routes');
const produitRoutes = require('./produit.routes');
const ordonnanceElectroniqueRoutes = require('./ordonnance-electronique.routes');
const inscriptionRoutes = require('./inscription.routes');
const publicationRoutes = require('./publication.routes');

router.use('/auth', authRoutes);
router.use('/inscriptions', inscriptionRoutes);
router.use('/patients', patientRoutes);
router.use('/carnet-medical', require('./carnet-medical.routes'));
router.use('/traitements', traitementRoutes);
router.use('/prises', priseRoutes);
router.use('/ordonnances', ordonnanceRoutes);
router.use('/ordonnances-electroniques', ordonnanceElectroniqueRoutes);
router.use('/statistiques', statistiqueRoutes);
router.use('/etablissements', etablissementRoutes);
router.use('/medecins', medecinRoutes);
router.use('/avis', avisRoutes);
router.use('/messagerie', messagerieRoutes);
router.use('/fichiers', fichierRoutes);
router.use('/rendez-vous', rendezvousRoutes);
router.use('/produits', produitRoutes);
router.use('/reservations-dispensaire', require('./reservation-dispensaire.routes'));
router.use('/notifications', require('./notification.routes'));
router.use('/publications', publicationRoutes);
router.use('/ai', require('./ai.routes'));
router.use('/commissions', require('./commission.routes'));
router.use('/paiements', require('./paiement.routes'));
router.use('/urgence', require('./urgence.routes'));
router.use('/demandes-prise-en-charge', require('./demande-prise-en-charge.routes'));
router.use('/famille', require('./famille.routes'));
router.use('/qr-medical', require('./qr-medical.routes'));
router.use('/admin', require('./admin.routes'));

module.exports = router;
